on:
    workflow_dispatch
env:
<<<<<<< HEAD
    targetEnv: dev
=======
    targetEnv: prod

>>>>>>> 0645f5b5af57b9f2df2d5de19a916235427ef2e1
name: Azure Bicep
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            # Checkout code
        - uses: actions/checkout@main
            # Log into Azure            
        - uses: azure/login@v1
          with:
              creds: ${{ secrets.AZURE_CREDNTIALS }}
            # Deploy ARM template
        - name: Run ARM deploy
          uses: azure/arm-deploy@v1
          with:
              subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
              resourceGroupName: ${{ secrets.AZURE_RG }}
              template: ./InfrastructureAsCode/main.bicep
              parameters: environment=${{ env.targetEnv }} 
